[package]
name = "ic-websocket-cdk"
version = "0.0.1"
description = "IC WebSocket Motoko CDK"
repository = ""
keywords = [ ]
license = "MIT"

[dependencies]
ic-certification = "0.1.1"
sha2 = "0.0.2"
base = "0.9.1"
cbor = "0.1.3"